name: eshop_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-96.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: GreyQo-Regular
      fonts:
        - asset: fonts/GreyQo-Regular.ttf

    - family: SourceSerifPro
      fonts:
        - asset: fonts/SourceSerifPro-Regular.ttf